use anyhow::Result;

use crate::tir::lower::Lowering;
use crate::tir::{builtin::BuiltinFn, CallResult, TirExpr, ValueType};

use super::lower_fixed_expr_method;

pub fn lower_bytes_method_call(
    ctx: &mut Lowering,
    line: usize,
    obj: TirExpr,
    method_name: &str,
    args: Vec<TirExpr>,
) -> Result<CallResult> {
    match method_name {
        "capitalize" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesCapitalize,
            ValueType::Bytes,
        ),
        "center" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Int, ValueType::Bytes],
            BuiltinFn::BytesCenter,
            ValueType::Bytes,
        ),
        "count" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesCount,
            ValueType::Int,
        ),
        "decode" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesDecode,
            ValueType::Str,
        ),
        "endswith" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesEndsWith,
            ValueType::Bool,
        ),
        "expandtabs" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Int],
            BuiltinFn::BytesExpandTabs,
            ValueType::Bytes,
        ),
        "find" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesFind,
            ValueType::Int,
        ),
        "fromhex" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Str],
            BuiltinFn::BytesFromHex,
            ValueType::Bytes,
        ),
        "hex" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesHex,
            ValueType::Str,
        ),
        "index" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesIndex,
            ValueType::Int,
        ),
        "isalnum" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesIsAlnum,
            ValueType::Bool,
        ),
        "isalpha" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesIsAlpha,
            ValueType::Bool,
        ),
        "isascii" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesIsAscii,
            ValueType::Bool,
        ),
        "isdigit" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesIsDigit,
            ValueType::Bool,
        ),
        "islower" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesIsLower,
            ValueType::Bool,
        ),
        "isspace" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesIsSpace,
            ValueType::Bool,
        ),
        "istitle" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesIsTitle,
            ValueType::Bool,
        ),
        "isupper" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesIsUpper,
            ValueType::Bool,
        ),
        "join" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::List(Box::new(ValueType::Bytes))],
            BuiltinFn::BytesJoin,
            ValueType::Bytes,
        ),
        "ljust" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Int, ValueType::Bytes],
            BuiltinFn::BytesLJust,
            ValueType::Bytes,
        ),
        "lower" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesLower,
            ValueType::Bytes,
        ),
        "lstrip" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesLStrip,
            ValueType::Bytes,
        ),
        "maketrans" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes, ValueType::Bytes],
            BuiltinFn::BytesMakeTrans,
            ValueType::Bytes,
        ),
        "partition" => {
            let tuple_class = ctx.get_or_create_tuple_class(&[
                ValueType::Bytes,
                ValueType::Bytes,
                ValueType::Bytes,
            ]);
            lower_fixed_expr_method(
                ctx,
                line,
                "bytes",
                obj,
                method_name,
                args,
                &[ValueType::Bytes],
                BuiltinFn::BytesPartition,
                ValueType::Class(tuple_class),
            )
        }
        "removeprefix" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesRemovePrefix,
            ValueType::Bytes,
        ),
        "removesuffix" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesRemoveSuffix,
            ValueType::Bytes,
        ),
        "replace" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes, ValueType::Bytes],
            BuiltinFn::BytesReplace,
            ValueType::Bytes,
        ),
        "rfind" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesRFind,
            ValueType::Int,
        ),
        "rindex" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesRIndex,
            ValueType::Int,
        ),
        "rjust" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Int, ValueType::Bytes],
            BuiltinFn::BytesRJust,
            ValueType::Bytes,
        ),
        "rpartition" => {
            let tuple_class = ctx.get_or_create_tuple_class(&[
                ValueType::Bytes,
                ValueType::Bytes,
                ValueType::Bytes,
            ]);
            lower_fixed_expr_method(
                ctx,
                line,
                "bytes",
                obj,
                method_name,
                args,
                &[ValueType::Bytes],
                BuiltinFn::BytesRPartition,
                ValueType::Class(tuple_class),
            )
        }
        "rsplit" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesRSplit,
            ValueType::List(Box::new(ValueType::Bytes)),
        ),
        "rstrip" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesRStrip,
            ValueType::Bytes,
        ),
        "split" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesSplit,
            ValueType::List(Box::new(ValueType::Bytes)),
        ),
        "splitlines" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesSplitLines,
            ValueType::List(Box::new(ValueType::Bytes)),
        ),
        "startswith" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesStartsWith,
            ValueType::Bool,
        ),
        "strip" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesStrip,
            ValueType::Bytes,
        ),
        "swapcase" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesSwapCase,
            ValueType::Bytes,
        ),
        "title" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesTitle,
            ValueType::Bytes,
        ),
        "translate" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::BytesTranslate,
            ValueType::Bytes,
        ),
        "upper" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::BytesUpper,
            ValueType::Bytes,
        ),
        "zfill" => lower_fixed_expr_method(
            ctx,
            line,
            "bytes",
            obj,
            method_name,
            args,
            &[ValueType::Int],
            BuiltinFn::BytesZFill,
            ValueType::Bytes,
        ),
        _ => Err(ctx.attribute_error(line, format!("{} has no method `{}`", "bytes", method_name))),
    }
}
