use anyhow::Result;

use crate::tir::lower::Lowering;
use crate::tir::{builtin::BuiltinFn, CallResult, TirExpr, ValueType};

use super::{lower_fixed_expr_method, lower_fixed_void_method};

pub fn lower_bytearray_method_call(
    ctx: &mut Lowering,
    line: usize,
    obj: TirExpr,
    method_name: &str,
    args: Vec<TirExpr>,
) -> Result<CallResult> {
    match method_name {
        "append" => lower_fixed_void_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int],
            BuiltinFn::ByteArrayAppend,
        ),
        "extend" => lower_fixed_void_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayExtend,
        ),
        "clear" => lower_fixed_void_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayClear,
        ),
        "insert" => lower_fixed_void_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int, ValueType::Int],
            BuiltinFn::ByteArrayInsert,
        ),
        "remove" => lower_fixed_void_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int],
            BuiltinFn::ByteArrayRemove,
        ),
        "reverse" => lower_fixed_void_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayReverse,
        ),
        "copy" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayCopy,
            ValueType::ByteArray,
        ),
        "pop" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayPop,
            ValueType::Int,
        ),
        "capitalize" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayCapitalize,
            ValueType::ByteArray,
        ),
        "center" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int, ValueType::Bytes],
            BuiltinFn::ByteArrayCenter,
            ValueType::ByteArray,
        ),
        "count" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayCount,
            ValueType::Int,
        ),
        "decode" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayDecode,
            ValueType::Str,
        ),
        "endswith" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayEndsWith,
            ValueType::Bool,
        ),
        "expandtabs" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int],
            BuiltinFn::ByteArrayExpandTabs,
            ValueType::ByteArray,
        ),
        "find" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayFind,
            ValueType::Int,
        ),
        "fromhex" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Str],
            BuiltinFn::ByteArrayFromHex,
            ValueType::ByteArray,
        ),
        "hex" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayHex,
            ValueType::Str,
        ),
        "index" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayIndex,
            ValueType::Int,
        ),
        "isalnum" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayIsAlnum,
            ValueType::Bool,
        ),
        "isalpha" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayIsAlpha,
            ValueType::Bool,
        ),
        "isascii" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayIsAscii,
            ValueType::Bool,
        ),
        "isdigit" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayIsDigit,
            ValueType::Bool,
        ),
        "islower" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayIsLower,
            ValueType::Bool,
        ),
        "isspace" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayIsSpace,
            ValueType::Bool,
        ),
        "istitle" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayIsTitle,
            ValueType::Bool,
        ),
        "isupper" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayIsUpper,
            ValueType::Bool,
        ),
        "join" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::List(Box::new(ValueType::ByteArray))],
            BuiltinFn::ByteArrayJoin,
            ValueType::ByteArray,
        ),
        "ljust" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int, ValueType::Bytes],
            BuiltinFn::ByteArrayLJust,
            ValueType::ByteArray,
        ),
        "lower" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayLower,
            ValueType::ByteArray,
        ),
        "lstrip" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayLStrip,
            ValueType::ByteArray,
        ),
        "maketrans" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes, ValueType::Bytes],
            BuiltinFn::ByteArrayMakeTrans,
            ValueType::Bytes,
        ),
        "partition" => {
            let tuple_class = ctx.get_or_create_tuple_class(&[
                ValueType::ByteArray,
                ValueType::ByteArray,
                ValueType::ByteArray,
            ]);
            lower_fixed_expr_method(
                ctx,
                line,
                "bytearray",
                obj,
                method_name,
                args,
                &[ValueType::Bytes],
                BuiltinFn::ByteArrayPartition,
                ValueType::Class(tuple_class),
            )
        }
        "removeprefix" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayRemovePrefix,
            ValueType::ByteArray,
        ),
        "removesuffix" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayRemoveSuffix,
            ValueType::ByteArray,
        ),
        "replace" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes, ValueType::Bytes],
            BuiltinFn::ByteArrayReplace,
            ValueType::ByteArray,
        ),
        "rfind" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayRFind,
            ValueType::Int,
        ),
        "rindex" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayRIndex,
            ValueType::Int,
        ),
        "rjust" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int, ValueType::Bytes],
            BuiltinFn::ByteArrayRJust,
            ValueType::ByteArray,
        ),
        "rpartition" => {
            let tuple_class = ctx.get_or_create_tuple_class(&[
                ValueType::ByteArray,
                ValueType::ByteArray,
                ValueType::ByteArray,
            ]);
            lower_fixed_expr_method(
                ctx,
                line,
                "bytearray",
                obj,
                method_name,
                args,
                &[ValueType::Bytes],
                BuiltinFn::ByteArrayRPartition,
                ValueType::Class(tuple_class),
            )
        }
        "rsplit" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayRSplit,
            ValueType::List(Box::new(ValueType::ByteArray)),
        ),
        "rstrip" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayRStrip,
            ValueType::ByteArray,
        ),
        "split" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArraySplit,
            ValueType::List(Box::new(ValueType::ByteArray)),
        ),
        "splitlines" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArraySplitLines,
            ValueType::List(Box::new(ValueType::ByteArray)),
        ),
        "startswith" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayStartsWith,
            ValueType::Bool,
        ),
        "strip" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayStrip,
            ValueType::ByteArray,
        ),
        "swapcase" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArraySwapCase,
            ValueType::ByteArray,
        ),
        "title" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayTitle,
            ValueType::ByteArray,
        ),
        "translate" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Bytes],
            BuiltinFn::ByteArrayTranslate,
            ValueType::ByteArray,
        ),
        "upper" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[],
            BuiltinFn::ByteArrayUpper,
            ValueType::ByteArray,
        ),
        "zfill" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int],
            BuiltinFn::ByteArrayZFill,
            ValueType::ByteArray,
        ),
        "__add__" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::ByteArray],
            BuiltinFn::ByteArrayConcat,
            ValueType::ByteArray,
        ),
        "__mul__" | "__rmul__" => lower_fixed_expr_method(
            ctx,
            line,
            "bytearray",
            obj,
            method_name,
            args,
            &[ValueType::Int],
            BuiltinFn::ByteArrayRepeat,
            ValueType::ByteArray,
        ),
        _ => Err(ctx.attribute_error(
            line,
            format!("{} has no method `{}`", "bytearray", method_name),
        )),
    }
}
